[package]
name = "My Project!"
version = "0.1.0"

[build]
infiles = ["./main.hc", "./main2.hc"]
outfile = "./a.wasm"
docfile = "./docs.md"

[dependencies.TestProject2]
name = "TestProject2"
source = 'C:\Users\lofty\Documents\Test2'
version = "0.2.0"
